### ISSUE TITLE
Children of FeatureHub provider (react SDK) should be typed as ReactNode rather than JSX.Element

### ISSUE THREAD

**Issue by GrandPoohBear** [featurehub-io/featurehub-javascript-sdk#181]
**Describe the bug**
The Typescript type definition specifies the children of the FeatureHub provider to be a `JSX.Element`.  While this is true in most cases, the more accurate representation is `ReactNode` which can express things that React is willing to accept as children, like strings, numbers, booleans, etc. (see here for reference: https://www.totaltypescript.com/jsx-element-vs-react-reactnode).  While this is a nitpicky thing, it does make for a conflict with some strict type systems.

 Which area does this issue belong to?

* [x] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Use typescript
2. In a component, add something like:
```
return (
<FeatureHub url="..." apiKey="...">{"Foo Bar Baz"}</FeatureHub>
)
```
3. See `tsc` fail, even though this is a valid (albeit contrived) example.

**Expected behavior**
`tsc` would properly typecheck.

**Versions**
 - React SDK version 1.2.0

**Comment by rvowles** [comment]
Sorry, missed this PR. 👀

**Comment by GrandPoohBear** [comment]
No worries!  Just kinda snuck up on y'all. 😜

**Comment by rvowles** [comment]
Forgot to close this issue with the merge!
