### ISSUE TITLE
Support for adding a header in a http request

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub-javascript-sdk#32]
**Is your feature request related to a problem? Please describe.**
Our connectivity from client to FHIO is through a API gateway and it requires authentication. We would need a way in the client sdk client to pass custom headers (along with the ones FHIO already sends) while talking to edge server

**Describe the solution you'd like**
Enhancement in API to add custom headers that the client would carry while making the request.

**Comment by IrinaSouth** [comment]
released in v1.1.5
